# RStudio settings, good practise


<!-- Moved installation here for now. -->

## Installation



```{block}
* Download R 
```

https://www.r-project.org/

```{block}
* Install RStudio
```

https://www.rstudio.com/products/rstudio/

```{block}

* Install packages (copy these lines into the Console in RStudio):
```

```{r, eval = FALSE}
install.packages("tidyverse")

install.packages("gapminder")

install.packages("gmodels")

install.packages("Hmisc")

install.packages("devtools")

devtools::install_github("ewenharrison/finalfit")

install.packages("pROC")

install.packages("survminer")

```

```{block}
When working with data, don't copy or type code directly into the Console. We will only be using the Console for viewing output, warnings, and errors (and installing packages as in the previous section). All code should be in a script and executed (=Run) using Control+Enter (line or section) or Control+Shift+Enter (whole script). Make sure you are always working in a project (the right-top corner of your RStudio interface should say "HealthyR").
```


## Script vs Console

Throughout this course, don't copy or type code directly into the Console. 
We will only be using the Console for viewing output, warnings, and errors. 
All code should be in a script and executed (=run) using Ctrl+Enter (line or section) or Ctrl+Shift+Enter (whole script). 
Make sure you are always working in a project (the right-top corner of your RStudio interface should say "HealthyR").


## Starting with a blank canvas

In the first session we loaded some data that we then plotted. 
When we import data, R stores it and displays it in the Environment tab.

It's good practice to restart R before commencing new work. This is to avoid accidentally using the wrong data or functions stored in the environment.  
Restarting R only takes a second!

* Restart R (Ctrl+Shift+F10 or select it from Session -> Restart R).

RStudio has a default setting that is no longer considered best practice. You should do this once:

* Go to Tools -> Global Options -> General and set "Save .RData on exit" to Never. 
This does not mean you can't or shouldn't save your work in .RData files. 
But it is best to do it consciously and load exactly what you need to load, rather than letting R always save and load everything for you, as this could also include broken data or objects.

