<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>HealthyR: R for healthcare data analysis</title>
  <meta name="description" content="A HealthyR texbook for our 2.5-day quickstart training course.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="HealthyR: R for healthcare data analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/healthyr_book_cover.png" />
  <meta property="og:description" content="A HealthyR texbook for our 2.5-day quickstart training course." />
  <meta name="github-repo" content="SurgicalInformatics/healthyr_book/" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="HealthyR: R for healthcare data analysis" />
  
  <meta name="twitter:description" content="A HealthyR texbook for our 2.5-day quickstart training course." />
  <meta name="twitter:image" content="images/healthyr_book_cover.png" />

<meta name="author" content="Ewen Harrison and Riinu Ots">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="definitions.html">
<link rel="next" href="time-to-event-data-survival.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for healthcare data analysis</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a><ul>
<li class="chapter" data-level="0.1" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>0.1</b> Installation</a></li>
</ul></li>
<li class="part"><span><b>I Always plot your data first</b></span></li>
<li class="chapter" data-level="1" data-path="your-first-r-plots.html"><a href="your-first-r-plots.html"><i class="fa fa-check"></i><b>1</b> Your first R plots</a><ul>
<li class="chapter" data-level="1.1" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>1.1</b> Data</a></li>
<li class="chapter" data-level="1.2" data-path="first-plot.html"><a href="first-plot.html"><i class="fa fa-check"></i><b>1.2</b> First plot</a><ul>
<li class="chapter" data-level="1.2.1" data-path="first-plot.html"><a href="first-plot.html#question"><i class="fa fa-check"></i><b>1.2.1</b> Question</a></li>
<li class="chapter" data-level="1.2.2" data-path="first-plot.html"><a href="first-plot.html#exercise"><i class="fa fa-check"></i><b>1.2.2</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="comparing-bars-of-different-height.html"><a href="comparing-bars-of-different-height.html"><i class="fa fa-check"></i><b>1.3</b> Comparing bars of different height</a><ul>
<li class="chapter" data-level="1.3.1" data-path="comparing-bars-of-different-height.html"><a href="comparing-bars-of-different-height.html#stretch-each-bar-to-100"><i class="fa fa-check"></i><b>1.3.1</b> Stretch each bar to 100%</a></li>
<li class="chapter" data-level="1.3.2" data-path="comparing-bars-of-different-height.html"><a href="comparing-bars-of-different-height.html#plot-each-bar-next-to-each-other"><i class="fa fa-check"></i><b>1.3.2</b> Plot each bar next to each other</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="facets-panels.html"><a href="facets-panels.html"><i class="fa fa-check"></i><b>1.4</b> Facets (panels)</a></li>
<li class="chapter" data-level="1.5" data-path="extra-using-aethetics-outside-of-the-aes.html"><a href="extra-using-aethetics-outside-of-the-aes.html"><i class="fa fa-check"></i><b>1.5</b> Extra: using aethetics outside of the aes()</a><ul>
<li class="chapter" data-level="1.5.1" data-path="extra-using-aethetics-outside-of-the-aes.html"><a href="extra-using-aethetics-outside-of-the-aes.html#setting-a-constant-fill"><i class="fa fa-check"></i><b>1.5.1</b> Setting a constant fill</a></li>
<li class="chapter" data-level="1.5.2" data-path="extra-using-aethetics-outside-of-the-aes.html"><a href="extra-using-aethetics-outside-of-the-aes.html#exercise-1"><i class="fa fa-check"></i><b>1.5.2</b> Exercise</a></li>
<li class="chapter" data-level="1.5.3" data-path="extra-using-aethetics-outside-of-the-aes.html"><a href="extra-using-aethetics-outside-of-the-aes.html#exercise-2"><i class="fa fa-check"></i><b>1.5.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="two-geoms-for-barplots-geom-bar-or-geom-col.html"><a href="two-geoms-for-barplots-geom-bar-or-geom-col.html"><i class="fa fa-check"></i><b>1.6</b> Two geoms for barplots: <code>geom_bar()</code> or <code>geom_col()</code></a></li>
<li class="chapter" data-level="1.7" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>1.7</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>2</b> R Basics</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-help.html"><a href="getting-help.html"><i class="fa fa-check"></i><b>2.1</b> Getting help</a><ul>
<li class="chapter" data-level="2.1.1" data-path="getting-help.html"><a href="getting-help.html#exercise-3"><i class="fa fa-check"></i><b>2.1.1</b> Exercise</a></li>
<li class="chapter" data-level="2.1.2" data-path="getting-help.html"><a href="getting-help.html#other-ways-to-investigate-objects"><i class="fa fa-check"></i><b>2.1.2</b> Other ways to investigate objects</a></li>
<li class="chapter" data-level="2.1.3" data-path="getting-help.html"><a href="getting-help.html#exercise-4"><i class="fa fa-check"></i><b>2.1.3</b> Exercise</a></li>
<li class="chapter" data-level="2.1.4" data-path="getting-help.html"><a href="getting-help.html#exercise-5"><i class="fa fa-check"></i><b>2.1.4</b> Exercise</a></li>
<li class="chapter" data-level="2.1.5" data-path="getting-help.html"><a href="getting-help.html#characters"><i class="fa fa-check"></i><b>2.1.5</b> Characters</a></li>
<li class="chapter" data-level="2.1.6" data-path="getting-help.html"><a href="getting-help.html#factors"><i class="fa fa-check"></i><b>2.1.6</b> Factors</a></li>
<li class="chapter" data-level="2.1.7" data-path="getting-help.html"><a href="getting-help.html#numbers"><i class="fa fa-check"></i><b>2.1.7</b> Numbers</a></li>
<li class="chapter" data-level="2.1.8" data-path="getting-help.html"><a href="getting-help.html#specifying-variable-types"><i class="fa fa-check"></i><b>2.1.8</b> Specifying variable types</a></li>
<li class="chapter" data-level="2.1.9" data-path="getting-help.html"><a href="getting-help.html#exercise-7"><i class="fa fa-check"></i><b>2.1.9</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="importing-data.html"><a href="importing-data.html"><i class="fa fa-check"></i><b>2.2</b> Importing data</a></li>
<li class="chapter" data-level="2.3" data-path="rounding-numbers.html"><a href="rounding-numbers.html"><i class="fa fa-check"></i><b>2.3</b> Rounding numbers</a><ul>
<li class="chapter" data-level="2.3.1" data-path="rounding-numbers.html"><a href="rounding-numbers.html#exercise-8"><i class="fa fa-check"></i><b>2.3.1</b> Exercise</a></li>
<li class="chapter" data-level="2.3.2" data-path="rounding-numbers.html"><a href="rounding-numbers.html#exercise-9"><i class="fa fa-check"></i><b>2.3.2</b> Exercise</a></li>
<li class="chapter" data-level="2.3.3" data-path="rounding-numbers.html"><a href="rounding-numbers.html#exercise-10"><i class="fa fa-check"></i><b>2.3.3</b> Exercise</a></li>
<li class="chapter" data-level="2.3.4" data-path="rounding-numbers.html"><a href="rounding-numbers.html#when-pipe-sends-data-to-the-wrong-place"><i class="fa fa-check"></i><b>2.3.4</b> When pipe sends data to the wrong place</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="solutions-1.html"><a href="solutions-1.html"><i class="fa fa-check"></i><b>2.4</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="summarising-data.html"><a href="summarising-data.html"><i class="fa fa-check"></i><b>3</b> Summarising data</a><ul>
<li class="chapter" data-level="3.1" data-path="data-1.html"><a href="data-1.html"><i class="fa fa-check"></i><b>3.1</b> Data</a></li>
<li class="chapter" data-level="3.2" data-path="tidyverse-packages-ggplot2-dplyr-tidyr-etc-.html"><a href="tidyverse-packages-ggplot2-dplyr-tidyr-etc-.html"><i class="fa fa-check"></i><b>3.2</b> Tidyverse packages: ggplot2, dplyr, tidyr, etc.</a></li>
<li class="chapter" data-level="3.3" data-path="basic-functions-for-summarising-data.html"><a href="basic-functions-for-summarising-data.html"><i class="fa fa-check"></i><b>3.3</b> Basic functions for summarising data</a></li>
<li class="chapter" data-level="3.4" data-path="subgroup-analysis-group-by-and-summarise.html"><a href="subgroup-analysis-group-by-and-summarise.html"><i class="fa fa-check"></i><b>3.4</b> Subgroup analysis: <code>group_by()</code> and <code>summarise()</code></a><ul>
<li class="chapter" data-level="3.4.1" data-path="subgroup-analysis-group-by-and-summarise.html"><a href="subgroup-analysis-group-by-and-summarise.html#exercise-11"><i class="fa fa-check"></i><b>3.4.1</b> Exercise</a></li>
<li class="chapter" data-level="3.4.2" data-path="subgroup-analysis-group-by-and-summarise.html"><a href="subgroup-analysis-group-by-and-summarise.html#exercise-12"><i class="fa fa-check"></i><b>3.4.2</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="mutate.html"><a href="mutate.html"><i class="fa fa-check"></i><b>3.5</b> <code>mutate()</code></a><ul>
<li class="chapter" data-level="3.5.1" data-path="mutate.html"><a href="mutate.html#exercise-13"><i class="fa fa-check"></i><b>3.5.1</b> Exercise</a></li>
<li class="chapter" data-level="3.5.2" data-path="mutate.html"><a href="mutate.html#optional-advanced-exercise"><i class="fa fa-check"></i><b>3.5.2</b> Optional advanced exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="wide-vs-long-spread-and-gather.html"><a href="wide-vs-long-spread-and-gather.html"><i class="fa fa-check"></i><b>3.6</b> Wide vs long: <code>spread()</code> and <code>gather()</code></a><ul>
<li class="chapter" data-level="3.6.1" data-path="wide-vs-long-spread-and-gather.html"><a href="wide-vs-long-spread-and-gather.html#wide-format"><i class="fa fa-check"></i><b>3.6.1</b> Wide format</a></li>
<li class="chapter" data-level="3.6.2" data-path="wide-vs-long-spread-and-gather.html"><a href="wide-vs-long-spread-and-gather.html#exercise-14"><i class="fa fa-check"></i><b>3.6.2</b> Exercise</a></li>
<li class="chapter" data-level="3.6.3" data-path="wide-vs-long-spread-and-gather.html"><a href="wide-vs-long-spread-and-gather.html#long-format"><i class="fa fa-check"></i><b>3.6.3</b> Long format</a></li>
<li class="chapter" data-level="3.6.4" data-path="wide-vs-long-spread-and-gather.html"><a href="wide-vs-long-spread-and-gather.html#exercise-15"><i class="fa fa-check"></i><b>3.6.4</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="sorting-arrange.html"><a href="sorting-arrange.html"><i class="fa fa-check"></i><b>3.7</b> Sorting: <code>arrange()</code></a></li>
<li class="chapter" data-level="3.8" data-path="factor-handling.html"><a href="factor-handling.html"><i class="fa fa-check"></i><b>3.8</b> Factor handling</a><ul>
<li class="chapter" data-level="3.8.1" data-path="factor-handling.html"><a href="factor-handling.html#exercise-16"><i class="fa fa-check"></i><b>3.8.1</b> Exercise</a></li>
<li class="chapter" data-level="3.8.2" data-path="factor-handling.html"><a href="factor-handling.html#fct_collapse---grouping-levels-together"><i class="fa fa-check"></i><b>3.8.2</b> <code>fct_collapse()</code> - grouping levels together</a></li>
<li class="chapter" data-level="3.8.3" data-path="factor-handling.html"><a href="factor-handling.html#fct_relevel---change-the-order-of-levels"><i class="fa fa-check"></i><b>3.8.3</b> <code>fct_relevel()</code> - change the order of levels</a></li>
<li class="chapter" data-level="3.8.4" data-path="factor-handling.html"><a href="factor-handling.html#fct_recode---rename-levels"><i class="fa fa-check"></i><b>3.8.4</b> <code>fct_recode()</code> - rename levels</a></li>
<li class="chapter" data-level="3.8.5" data-path="factor-handling.html"><a href="factor-handling.html#converting-factors-to-numbers"><i class="fa fa-check"></i><b>3.8.5</b> Converting factors to numbers</a></li>
<li class="chapter" data-level="3.8.6" data-path="factor-handling.html"><a href="factor-handling.html#exercise-17"><i class="fa fa-check"></i><b>3.8.6</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="long-exercise.html"><a href="long-exercise.html"><i class="fa fa-check"></i><b>3.9</b> Long Exercise</a></li>
<li class="chapter" data-level="3.10" data-path="extra-formatting-a-table-for-publication.html"><a href="extra-formatting-a-table-for-publication.html"><i class="fa fa-check"></i><b>3.10</b> Extra: formatting a table for publication</a></li>
<li class="chapter" data-level="3.11" data-path="solution-long-exercise.html"><a href="solution-long-exercise.html"><i class="fa fa-check"></i><b>3.11</b> Solution: Long Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="different-types-of-plots.html"><a href="different-types-of-plots.html"><i class="fa fa-check"></i><b>4</b> Different types of plots</a><ul>
<li class="chapter" data-level="4.1" data-path="data-2.html"><a href="data-2.html"><i class="fa fa-check"></i><b>4.1</b> Data</a></li>
<li class="chapter" data-level="4.2" data-path="scatter-plotsbubble-plots-geom-point.html"><a href="scatter-plotsbubble-plots-geom-point.html"><i class="fa fa-check"></i><b>4.2</b> Scatter plots/bubble plots - <code>geom_point()</code></a><ul>
<li class="chapter" data-level="4.2.1" data-path="scatter-plotsbubble-plots-geom-point.html"><a href="scatter-plotsbubble-plots-geom-point.html#exercise-18"><i class="fa fa-check"></i><b>4.2.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="line-charttimeplot-geom-line.html"><a href="line-charttimeplot-geom-line.html"><i class="fa fa-check"></i><b>4.3</b> Line chart/timeplot - <code>geom_line()</code></a><ul>
<li class="chapter" data-level="4.3.1" data-path="line-charttimeplot-geom-line.html"><a href="line-charttimeplot-geom-line.html#exercise-19"><i class="fa fa-check"></i><b>4.3.1</b> Exercise</a></li>
<li class="chapter" data-level="4.3.2" data-path="line-charttimeplot-geom-line.html"><a href="line-charttimeplot-geom-line.html#advanced-example"><i class="fa fa-check"></i><b>4.3.2</b> Advanced example</a></li>
<li class="chapter" data-level="4.3.3" data-path="line-charttimeplot-geom-line.html"><a href="line-charttimeplot-geom-line.html#advanced-exercise"><i class="fa fa-check"></i><b>4.3.3</b> Advanced Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="box-plot-geom-boxplot.html"><a href="box-plot-geom-boxplot.html"><i class="fa fa-check"></i><b>4.4</b> Box-plot - <code>geom_boxplot()</code></a><ul>
<li class="chapter" data-level="4.4.1" data-path="box-plot-geom-boxplot.html"><a href="box-plot-geom-boxplot.html#exercise-20"><i class="fa fa-check"></i><b>4.4.1</b> Exercise</a></li>
<li class="chapter" data-level="4.4.2" data-path="box-plot-geom-boxplot.html"><a href="box-plot-geom-boxplot.html#dot-plot---geom_dotplot"><i class="fa fa-check"></i><b>4.4.2</b> Dot-plot - <code>geom_dotplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="barplot-geom-bar-and-geom-col.html"><a href="barplot-geom-bar-and-geom-col.html"><i class="fa fa-check"></i><b>4.5</b> Barplot - <code>geom_bar()</code> and <code>geom_col()</code></a><ul>
<li class="chapter" data-level="4.5.1" data-path="barplot-geom-bar-and-geom-col.html"><a href="barplot-geom-bar-and-geom-col.html#exercise-21"><i class="fa fa-check"></i><b>4.5.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="all-other-types-of-plots.html"><a href="all-other-types-of-plots.html"><i class="fa fa-check"></i><b>4.6</b> All other types of plots</a></li>
<li class="chapter" data-level="4.7" data-path="specifying-aes-variables.html"><a href="specifying-aes-variables.html"><i class="fa fa-check"></i><b>4.7</b> Specifying <code>aes()</code> variables</a></li>
<li class="chapter" data-level="4.8" data-path="extra-optional-exercises.html"><a href="extra-optional-exercises.html"><i class="fa fa-check"></i><b>4.8</b> Extra: Optional exercises</a><ul>
<li class="chapter" data-level="4.8.1" data-path="extra-optional-exercises.html"><a href="extra-optional-exercises.html#exercise-22"><i class="fa fa-check"></i><b>4.8.1</b> Exercise</a></li>
<li class="chapter" data-level="4.8.2" data-path="extra-optional-exercises.html"><a href="extra-optional-exercises.html#exercise-23"><i class="fa fa-check"></i><b>4.8.2</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="solutions-2.html"><a href="solutions-2.html"><i class="fa fa-check"></i><b>4.9</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="fine-tuning-plots.html"><a href="fine-tuning-plots.html"><i class="fa fa-check"></i><b>5</b> Fine tuning plots</a><ul>
<li class="chapter" data-level="5.1" data-path="data-and-initial-plot.html"><a href="data-and-initial-plot.html"><i class="fa fa-check"></i><b>5.1</b> Data and initial plot</a></li>
<li class="chapter" data-level="5.2" data-path="scales.html"><a href="scales.html"><i class="fa fa-check"></i><b>5.2</b> Scales</a><ul>
<li class="chapter" data-level="5.2.1" data-path="scales.html"><a href="scales.html#logarithmic"><i class="fa fa-check"></i><b>5.2.1</b> Logarithmic</a></li>
<li class="chapter" data-level="5.2.2" data-path="scales.html"><a href="scales.html#expand-limits"><i class="fa fa-check"></i><b>5.2.2</b> Expand limits</a></li>
<li class="chapter" data-level="5.2.3" data-path="scales.html"><a href="scales.html#zoom-in"><i class="fa fa-check"></i><b>5.2.3</b> Zoom in</a></li>
<li class="chapter" data-level="5.2.4" data-path="scales.html"><a href="scales.html#axis-ticks"><i class="fa fa-check"></i><b>5.2.4</b> Axis ticks</a></li>
<li class="chapter" data-level="5.2.5" data-path="scales.html"><a href="scales.html#swap-the-axes"><i class="fa fa-check"></i><b>5.2.5</b> Swap the axes</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="colours.html"><a href="colours.html"><i class="fa fa-check"></i><b>5.3</b> Colours</a><ul>
<li class="chapter" data-level="5.3.1" data-path="colours.html"><a href="colours.html#using-the-brewer-palettes"><i class="fa fa-check"></i><b>5.3.1</b> Using the Brewer palettes:</a></li>
<li class="chapter" data-level="5.3.2" data-path="colours.html"><a href="colours.html#legend-title"><i class="fa fa-check"></i><b>5.3.2</b> Legend title</a></li>
<li class="chapter" data-level="5.3.3" data-path="colours.html"><a href="colours.html#choosing-colours-manually"><i class="fa fa-check"></i><b>5.3.3</b> Choosing colours manually</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="titles-and-labels.html"><a href="titles-and-labels.html"><i class="fa fa-check"></i><b>5.4</b> Titles and labels</a><ul>
<li class="chapter" data-level="5.4.1" data-path="titles-and-labels.html"><a href="titles-and-labels.html#annotation"><i class="fa fa-check"></i><b>5.4.1</b> Annotation</a></li>
<li class="chapter" data-level="5.4.2" data-path="titles-and-labels.html"><a href="titles-and-labels.html#annotation-with-a-superscript-and-a-variable"><i class="fa fa-check"></i><b>5.4.2</b> Annotation with a superscript and a variable</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="text-size.html"><a href="text-size.html"><i class="fa fa-check"></i><b>5.5</b> Text size</a><ul>
<li class="chapter" data-level="5.5.1" data-path="text-size.html"><a href="text-size.html#legend-position"><i class="fa fa-check"></i><b>5.5.1</b> Legend position</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="saving-your-plot.html"><a href="saving-your-plot.html"><i class="fa fa-check"></i><b>5.6</b> Saving your plot</a></li>
</ul></li>
<li class="part"><span><b>II Medical Statistics</b></span></li>
<li class="chapter" data-level="6" data-path="tests-for-continuous-outcome-variables.html"><a href="tests-for-continuous-outcome-variables.html"><i class="fa fa-check"></i><b>6</b> Tests for continuous outcome variables</a><ul>
<li class="chapter" data-level="6.1" data-path="load-data.html"><a href="load-data.html"><i class="fa fa-check"></i><b>6.1</b> Load data</a></li>
<li class="chapter" data-level="6.2" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>6.2</b> T-test</a><ul>
<li class="chapter" data-level="6.2.1" data-path="t-test.html"><a href="t-test.html#plotting"><i class="fa fa-check"></i><b>6.2.1</b> Plotting</a></li>
<li class="chapter" data-level="6.2.2" data-path="t-test.html"><a href="t-test.html#histogram-for-each-continent"><i class="fa fa-check"></i><b>6.2.2</b> Histogram for each continent</a></li>
<li class="chapter" data-level="6.2.3" data-path="t-test.html"><a href="t-test.html#boxplot-of-2-years"><i class="fa fa-check"></i><b>6.2.3</b> Boxplot of 2 years</a></li>
<li class="chapter" data-level="6.2.4" data-path="t-test.html"><a href="t-test.html#exercise-24"><i class="fa fa-check"></i><b>6.2.4</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="two-sample-t-tests.html"><a href="two-sample-t-tests.html"><i class="fa fa-check"></i><b>6.3</b> Two-sample t-tests</a><ul>
<li class="chapter" data-level="6.3.1" data-path="two-sample-t-tests.html"><a href="two-sample-t-tests.html#t-test-output"><i class="fa fa-check"></i><b>6.3.1</b> T-Test output</a></li>
<li class="chapter" data-level="6.3.2" data-path="two-sample-t-tests.html"><a href="two-sample-t-tests.html#exercise-25"><i class="fa fa-check"></i><b>6.3.2</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html"><i class="fa fa-check"></i><b>6.4</b> One sample t-tests</a><ul>
<li class="chapter" data-level="6.4.1" data-path="one-sample-t-tests.html"><a href="one-sample-t-tests.html#exercise-26"><i class="fa fa-check"></i><b>6.4.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>6.5</b> ANOVA</a><ul>
<li class="chapter" data-level="6.5.1" data-path="anova.html"><a href="anova.html#plotting-1"><i class="fa fa-check"></i><b>6.5.1</b> Plotting</a></li>
<li class="chapter" data-level="6.5.2" data-path="anova.html"><a href="anova.html#analysis"><i class="fa fa-check"></i><b>6.5.2</b> Analysis</a></li>
<li class="chapter" data-level="6.5.3" data-path="anova.html"><a href="anova.html#check-assumptions"><i class="fa fa-check"></i><b>6.5.3</b> Check assumptions</a></li>
<li class="chapter" data-level="6.5.4" data-path="anova.html"><a href="anova.html#perform-pairwise-tests"><i class="fa fa-check"></i><b>6.5.4</b> Perform pairwise tests</a></li>
<li class="chapter" data-level="6.5.5" data-path="anova.html"><a href="anova.html#top-tip-the-cut-function"><i class="fa fa-check"></i><b>6.5.5</b> Top tip: the cut() function</a></li>
<li class="chapter" data-level="6.5.6" data-path="anova.html"><a href="anova.html#exercise-27"><i class="fa fa-check"></i><b>6.5.6</b> Exercise</a></li>
<li class="chapter" data-level="6.5.7" data-path="anova.html"><a href="anova.html#exercise-28"><i class="fa fa-check"></i><b>6.5.7</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="non-parametric-data.html"><a href="non-parametric-data.html"><i class="fa fa-check"></i><b>6.6</b> Non-parametric data</a><ul>
<li class="chapter" data-level="6.6.1" data-path="non-parametric-data.html"><a href="non-parametric-data.html#plotting-2"><i class="fa fa-check"></i><b>6.6.1</b> Plotting</a></li>
<li class="chapter" data-level="6.6.2" data-path="non-parametric-data.html"><a href="non-parametric-data.html#exercise-non-parametric-testing"><i class="fa fa-check"></i><b>6.6.2</b> Exercise: Non-parametric testing</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="solutions-3.html"><a href="solutions-3.html"><i class="fa fa-check"></i><b>6.7</b> Solutions</a></li>
<li class="chapter" data-level="6.8" data-path="advanced-example-1.html"><a href="advanced-example-1.html"><i class="fa fa-check"></i><b>6.8</b> Advanced example</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>7</b> Linear regression</a><ul>
<li class="chapter" data-level="7.1" data-path="data-3.html"><a href="data-3.html"><i class="fa fa-check"></i><b>7.1</b> Data</a></li>
<li class="chapter" data-level="7.2" data-path="plotting-3.html"><a href="plotting-3.html"><i class="fa fa-check"></i><b>7.2</b> Plotting</a><ul>
<li class="chapter" data-level="7.2.1" data-path="plotting-3.html"><a href="plotting-3.html#exercise-29"><i class="fa fa-check"></i><b>7.2.1</b> Exercise</a></li>
<li class="chapter" data-level="7.2.2" data-path="plotting-3.html"><a href="plotting-3.html#exercise-30"><i class="fa fa-check"></i><b>7.2.2</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>7.3</b> Simple linear regression</a><ul>
<li class="chapter" data-level="7.3.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#exercise-31"><i class="fa fa-check"></i><b>7.3.1</b> Exercise</a></li>
<li class="chapter" data-level="7.3.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#model-information-summary-tidy-glance"><i class="fa fa-check"></i><b>7.3.2</b> Model information: <code>summary()</code>, <code>tidy()</code> ,<code>glance()</code></a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="if-you-are-new-to-linear-regression.html"><a href="if-you-are-new-to-linear-regression.html"><i class="fa fa-check"></i><b>7.4</b> If you are new to linear regression</a><ul>
<li class="chapter" data-level="7.4.1" data-path="if-you-are-new-to-linear-regression.html"><a href="if-you-are-new-to-linear-regression.html#exercise---residuals"><i class="fa fa-check"></i><b>7.4.1</b> Exercise - Residuals</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>7.5</b> Multiple linear regression</a><ul>
<li class="chapter" data-level="7.5.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercise-32"><i class="fa fa-check"></i><b>7.5.1</b> Exercise</a></li>
<li class="chapter" data-level="7.5.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercise-33"><i class="fa fa-check"></i><b>7.5.2</b> Exercise</a></li>
<li class="chapter" data-level="7.5.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#exercise-34"><i class="fa fa-check"></i><b>7.5.3</b> Exercise</a></li>
<li class="chapter" data-level="7.5.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#optional-advanced-exercise-1"><i class="fa fa-check"></i><b>7.5.4</b> Optional (Advanced) Exercise</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="very-advanced-example.html"><a href="very-advanced-example.html"><i class="fa fa-check"></i><b>7.6</b> Very advanced example</a></li>
<li class="chapter" data-level="7.7" data-path="solutions-4.html"><a href="solutions-4.html"><i class="fa fa-check"></i><b>7.7</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tests-for-categorical-variables.html"><a href="tests-for-categorical-variables.html"><i class="fa fa-check"></i><b>8</b> Tests for categorical variables</a><ul>
<li class="chapter" data-level="8.1" data-path="data-4.html"><a href="data-4.html"><i class="fa fa-check"></i><b>8.1</b> Data</a><ul>
<li class="chapter" data-level="8.1.1" data-path="data-4.html"><a href="data-4.html#recap-on-factors"><i class="fa fa-check"></i><b>8.1.1</b> Recap on factors</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="chi-squared-test-fishers-exact-test.html"><a href="chi-squared-test-fishers-exact-test.html"><i class="fa fa-check"></i><b>8.2</b> Chi-squared test / Fisher’s exact test</a><ul>
<li class="chapter" data-level="8.2.1" data-path="chi-squared-test-fishers-exact-test.html"><a href="chi-squared-test-fishers-exact-test.html#plotting-4"><i class="fa fa-check"></i><b>8.2.1</b> Plotting</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="analysis-1.html"><a href="analysis-1.html"><i class="fa fa-check"></i><b>8.3</b> Analysis</a><ul>
<li class="chapter" data-level="8.3.1" data-path="analysis-1.html"><a href="analysis-1.html#using-base-r"><i class="fa fa-check"></i><b>8.3.1</b> Using base R</a></li>
<li class="chapter" data-level="8.3.2" data-path="analysis-1.html"><a href="analysis-1.html#using-crosstable"><i class="fa fa-check"></i><b>8.3.2</b> Using <code>CrossTable</code></a></li>
<li class="chapter" data-level="8.3.3" data-path="analysis-1.html"><a href="analysis-1.html#exercise-35"><i class="fa fa-check"></i><b>8.3.3</b> Exercise</a></li>
<li class="chapter" data-level="8.3.4" data-path="analysis-1.html"><a href="analysis-1.html#fishers-exact-test"><i class="fa fa-check"></i><b>8.3.4</b> Fisher’s exact test</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="summarising-multiple-factors-optional.html"><a href="summarising-multiple-factors-optional.html"><i class="fa fa-check"></i><b>8.4</b> Summarising multiple factors (optional)</a></li>
<li class="chapter" data-level="8.5" data-path="summarising-factors-with-librarysummarizer.html"><a href="summarising-factors-with-librarysummarizer.html"><i class="fa fa-check"></i><b>8.5</b> Summarising factors with <code>library(summarizer)</code></a><ul>
<li class="chapter" data-level="8.5.1" data-path="summarising-factors-with-librarysummarizer.html"><a href="summarising-factors-with-librarysummarizer.html#summarising-factors-with-librarytidyverse"><i class="fa fa-check"></i><b>8.5.1</b> Summarising factors with <code>library(tidyverse)</code></a></li>
<li class="chapter" data-level="8.5.2" data-path="summarising-factors-with-librarysummarizer.html"><a href="summarising-factors-with-librarysummarizer.html#example"><i class="fa fa-check"></i><b>8.5.2</b> Example</a></li>
<li class="chapter" data-level="8.5.3" data-path="summarising-factors-with-librarysummarizer.html"><a href="summarising-factors-with-librarysummarizer.html#exercise-36"><i class="fa fa-check"></i><b>8.5.3</b> Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>9</b> Logistic regression</a><ul>
<li class="chapter" data-level="9.1" data-path="definitions.html"><a href="definitions.html"><i class="fa fa-check"></i><b>9.1</b> Definitions</a></li>
<li class="chapter" data-level="9.2" data-path="odds-and-probabilities.html"><a href="odds-and-probabilities.html"><i class="fa fa-check"></i><b>9.2</b> Odds and probabilities</a><ul>
<li class="chapter" data-level="9.2.1" data-path="odds-and-probabilities.html"><a href="odds-and-probabilities.html#odds-ratios"><i class="fa fa-check"></i><b>9.2.1</b> Odds ratios</a></li>
<li class="chapter" data-level="9.2.2" data-path="odds-and-probabilities.html"><a href="odds-and-probabilities.html#always-plot-your-data-first"><i class="fa fa-check"></i><b>9.2.2</b> Always plot your data first!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="time-to-event-data-survival.html"><a href="time-to-event-data-survival.html"><i class="fa fa-check"></i><b>10</b> Time-to-event data (survival)</a><ul>
<li class="chapter" data-level="10.1" data-path="data-5.html"><a href="data-5.html"><i class="fa fa-check"></i><b>10.1</b> Data</a></li>
<li class="chapter" data-level="10.2" data-path="kaplan-meier-survival-estimator.html"><a href="kaplan-meier-survival-estimator.html"><i class="fa fa-check"></i><b>10.2</b> Kaplan-Meier survival estimator</a><ul>
<li class="chapter" data-level="10.2.1" data-path="kaplan-meier-survival-estimator.html"><a href="kaplan-meier-survival-estimator.html#km-analysis-for-whole-cohort"><i class="fa fa-check"></i><b>10.2.1</b> KM analysis for whole cohort</a></li>
<li class="chapter" data-level="10.2.2" data-path="kaplan-meier-survival-estimator.html"><a href="kaplan-meier-survival-estimator.html#model"><i class="fa fa-check"></i><b>10.2.2</b> Model</a></li>
<li class="chapter" data-level="10.2.3" data-path="kaplan-meier-survival-estimator.html"><a href="kaplan-meier-survival-estimator.html#life-table"><i class="fa fa-check"></i><b>10.2.3</b> Life table</a></li>
<li class="chapter" data-level="10.2.4" data-path="kaplan-meier-survival-estimator.html"><a href="kaplan-meier-survival-estimator.html#km-plot"><i class="fa fa-check"></i><b>10.2.4</b> KM plot</a></li>
<li class="chapter" data-level="10.2.5" data-path="kaplan-meier-survival-estimator.html"><a href="kaplan-meier-survival-estimator.html#exercise-37"><i class="fa fa-check"></i><b>10.2.5</b> Exercise</a></li>
<li class="chapter" data-level="10.2.6" data-path="kaplan-meier-survival-estimator.html"><a href="kaplan-meier-survival-estimator.html#log-rank-test"><i class="fa fa-check"></i><b>10.2.6</b> Log-rank test</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="cox-proportional-hazard-regression.html"><a href="cox-proportional-hazard-regression.html"><i class="fa fa-check"></i><b>10.3</b> Cox proportional hazard regression</a><ul>
<li class="chapter" data-level="10.3.1" data-path="cox-proportional-hazard-regression.html"><a href="cox-proportional-hazard-regression.html#model-1"><i class="fa fa-check"></i><b>10.3.1</b> Model</a></li>
<li class="chapter" data-level="10.3.2" data-path="cox-proportional-hazard-regression.html"><a href="cox-proportional-hazard-regression.html#assumptions"><i class="fa fa-check"></i><b>10.3.2</b> Assumptions</a></li>
<li class="chapter" data-level="10.3.3" data-path="cox-proportional-hazard-regression.html"><a href="cox-proportional-hazard-regression.html#exercise-38"><i class="fa fa-check"></i><b>10.3.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="dates-in-r.html"><a href="dates-in-r.html"><i class="fa fa-check"></i><b>10.4</b> Dates in R</a><ul>
<li class="chapter" data-level="10.4.1" data-path="dates-in-r.html"><a href="dates-in-r.html#converting-dates-to-survival-time"><i class="fa fa-check"></i><b>10.4.1</b> Converting dates to survival time</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="solutions-5.html"><a href="solutions-5.html"><i class="fa fa-check"></i><b>10.5</b> Solutions</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">HealthyR: R for healthcare data analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="odds-and-probabilities" class="section level2">
<h2><span class="header-section-number">9.2</span> Odds and probabilities</h2>
<p>Odds and probabilities can get confusing so let’s get them straight:</p>
<p><img src="images/p_vs_odds2.png" /></p>
<p>Odds and probabilities can always be interconverted. For example, if the odds of a patient dying from a disease are <code>9 to 1</code> then the probability of death (also known as risk) is 10%. Odds of <code>1 to 1</code> equal 50%.</p>
<p><span class="math inline">\(Odds = \frac{p}{1-p}\)</span>, where <span class="math inline">\(p\)</span> is the probability of the outcome occuring (or the circle being red).</p>
<p>Look at the numbers and convince yourself that this works.</p>
<div id="odds-ratios" class="section level3">
<h3><span class="header-section-number">9.2.1</span> Odds ratios</h3>
<p>For a given categorical explanatory variable (e.g. gender), the likelihood of an outcome/dependent occuring (e.g cancer) can be expressed in a ratio of odds or odds ratio , e.g. the odds of men developing cancer is 2-times that of females, odds ratio = 2.0.</p>
<p><img src="images/or.png" /></p>
<p>An alternative is a ratio of probabilites, called a risk ratio or relative risk. Odds ratios have useful mathematical characteristics and are the main expression of results in logistic regression analysis.</p>

<p>##Melanoma dataset</p>
<p>Malignant Melanoma is a cancer of the skin. It is agressive and highly invasive, making it difficult to treat.</p>
<p>It’s classically divided into 4 stages of severity, based upon the depth of the tumour:</p>
<ul>
<li>Stage I- &lt;0.5 mm depth</li>
<li>Stage II- 0.5 to 1.0 mm depth</li>
<li>Stage III- 1.0 to 4.0 mm depth</li>
<li>Stage IV- &gt; 4.0 mm depth</li>
</ul>
<p>This will be important in our analysis as we will creating a new variable based upon this.</p>
<p>Using logistic regression, we will investigate factors associated with death from malignant melanoma.</p>
<p>###Doing logistic regression in R</p>
<p>There are a few different ways of creating a logistic regression in R. The <code>glm()</code> function is probably the most common and most flexible one to use. (<code>glm</code> stands for <code>generalised linear model</code>.)</p>
<p>Within the <code>glm()</code> function there are several <code>options</code> in the function we must define to make R run a logistic regression.</p>
<p><code>data</code> - you must define the dataframe to be used in the regression.</p>
<p><code>family</code> - this tells R to treat the analysis as a logisitic regression. For our purposes, <code>family</code> will always be <code>&quot;binomial&quot;</code> (as binary data follow this distribution).</p>
<p><code>x ~ a + b + c</code> - this is the formula for the logistic regression, with <code>x</code> being the outcome and <code>a</code>, <code>b</code> and <code>c</code> being predictor variables.</p>
<p>Note the outcome is separated from the rest of the formula and sits on the left hand side of a <code>~</code>. The confounding variables are on the right side, separated by a <code>+</code> sign.</p>
<p>The final <code>glm()</code> function takes the following form:</p>
<p><code>glm(x ~ a + b + c + d, data = data, family = &quot;binomial&quot;)</code></p>
<p>##Setting up your data</p>
<p>The most important step to ensure a good basis to start from is to ensure your variables are well structured and your outcome variable has exactly two outcomes.</p>
<p>We will need to make sure our outcome variables and predictor variables (the ones we want to adjust for) are suitably prepared.</p>
<p>In this example, the outcome variable called <code>status.factor</code> describes whether patients died or not and will be our (dependent) variable of interest.</p>
<p>###Worked Example</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb265-2" data-line-number="2"></a>
<a class="sourceLine" id="cb265-3" data-line-number="3"><span class="kw">load</span>(<span class="st">&quot;melanoma_factored.rda&quot;</span>)</a>
<a class="sourceLine" id="cb265-4" data-line-number="4"><span class="co">#Load in data from the previous session</span></a></code></pre></div>
<p>Here <code>status.factor</code> has three levels: <code>Died</code>, <code>Died - other causes</code> and <code>Alive</code>. This is not useful for us, as logistic regression requires outcomes to be binary.</p>
<p>We want to find out using logistic regression, which variables predict death from Melanoma. So we should create a new factor variable, <code>died_melanoma.factor</code>. This will have two outcomes, <code>Yes</code> (did die from melanoma) or <code>No</code> (did not die from melanoma).</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" data-line-number="1">mydata<span class="op">$</span>status.factor <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb266-2" data-line-number="2"><span class="st">  </span><span class="kw">fct_collapse</span>(<span class="st">&quot;Yes&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Died&quot;</span>),</a>
<a class="sourceLine" id="cb266-3" data-line-number="3">               <span class="st">&quot;No&quot;</span>  =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Alive&quot;</span>, <span class="st">&quot;Died - other causes&quot;</span>)) -&gt;</a>
<a class="sourceLine" id="cb266-4" data-line-number="4"><span class="st">  </span>mydata<span class="op">$</span>died_melanoma.factor</a>
<a class="sourceLine" id="cb266-5" data-line-number="5"></a>
<a class="sourceLine" id="cb266-6" data-line-number="6">mydata<span class="op">$</span>died_melanoma.factor <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">levels</span>()</a></code></pre></div>
<pre><code>## [1] &quot;No&quot;  &quot;Yes&quot;</code></pre>
<p>##Creating categories</p>
<p>Now we have set up our outcome variable, we should ensure our predictor variables are prepared too.</p>
<p>Remember the stages of Melanoma? This is an important predictor of Melanoma Mortality based upon the scientific literature.</p>
<p>We should take this into account in our model.</p>
<p>###Exercise</p>
<p>After sorting out your outcome variable, create a new variable called <code>stage.factor</code> to encompass the stages of melanoma based upon the thickness. In this data, the <code>thickness</code> variable is measured in millimetres too.</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" data-line-number="1"><span class="co">#the cut() function makes a continuous variable into a categorical variable</span></a>
<a class="sourceLine" id="cb268-2" data-line-number="2">mydata<span class="op">$</span>thickness <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb268-3" data-line-number="3"><span class="st">    </span><span class="kw">cut</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.5</span>,<span class="dv">1</span>,<span class="dv">4</span>, <span class="kw">max</span>(mydata<span class="op">$</span>thickness, <span class="dt">na.rm=</span>T)),</a>
<a class="sourceLine" id="cb268-4" data-line-number="4">            <span class="dt">include.lowest =</span> T) -&gt;</a>
<a class="sourceLine" id="cb268-5" data-line-number="5">mydata<span class="op">$</span>stage.factor</a>
<a class="sourceLine" id="cb268-6" data-line-number="6"></a>
<a class="sourceLine" id="cb268-7" data-line-number="7">mydata<span class="op">$</span>stage.factor <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">levels</span>()</a></code></pre></div>
<pre><code>## [1] &quot;[0,0.5]&quot;  &quot;(0.5,1]&quot;  &quot;(1,4]&quot;    &quot;(4,17.4]&quot;</code></pre>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" data-line-number="1">mydata<span class="op">$</span>stage.factor <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb270-2" data-line-number="2"><span class="st">  </span><span class="kw">fct_recode</span>(<span class="st">&quot;Stage I&quot;</span>   =<span class="st"> &quot;[0,0.5]&quot;</span>,</a>
<a class="sourceLine" id="cb270-3" data-line-number="3">             <span class="st">&quot;Stage II&quot;</span>  =<span class="st"> &quot;(0.5,1]&quot;</span>,</a>
<a class="sourceLine" id="cb270-4" data-line-number="4">             <span class="st">&quot;Stage III&quot;</span> =<span class="st"> &quot;(1,4]&quot;</span>,</a>
<a class="sourceLine" id="cb270-5" data-line-number="5">             <span class="st">&quot;Stage IV&quot;</span>  =<span class="st"> &quot;(4,17.4]&quot;</span></a>
<a class="sourceLine" id="cb270-6" data-line-number="6">    ) -&gt;<span class="st"> </span>mydata<span class="op">$</span>stage.factor</a>
<a class="sourceLine" id="cb270-7" data-line-number="7"></a>
<a class="sourceLine" id="cb270-8" data-line-number="8">mydata<span class="op">$</span>stage.factor <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">levels</span>()</a></code></pre></div>
<pre><code>## [1] &quot;Stage I&quot;   &quot;Stage II&quot;  &quot;Stage III&quot; &quot;Stage IV&quot;</code></pre>
</div>
<div id="always-plot-your-data-first" class="section level3">
<h3><span class="header-section-number">9.2.2</span> Always plot your data first!</h3>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" data-line-number="1"><span class="kw">source</span>(<span class="st">&quot;1_source_theme.R&quot;</span>)</a>
<a class="sourceLine" id="cb272-2" data-line-number="2"></a>
<a class="sourceLine" id="cb272-3" data-line-number="3">mydata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb272-4" data-line-number="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> sex.factor)) <span class="op">+</span></a>
<a class="sourceLine" id="cb272-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> sex.factor))</a></code></pre></div>
<p><img src="09_tests_categorical_files/figure-html/unnamed-chunk-4-1.png" width="288" /></p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" data-line-number="1">mydata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb273-2" data-line-number="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> ulcer.factor)) <span class="op">+</span></a>
<a class="sourceLine" id="cb273-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> ulcer.factor))</a></code></pre></div>
<p><img src="09_tests_categorical_files/figure-html/unnamed-chunk-5-1.png" width="288" /></p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" data-line-number="1">mydata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb274-2" data-line-number="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> stage.factor)) <span class="op">+</span></a>
<a class="sourceLine" id="cb274-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> stage.factor))</a></code></pre></div>
<p><img src="09_tests_categorical_files/figure-html/unnamed-chunk-6-1.png" width="384" /></p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" data-line-number="1">mydata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb275-2" data-line-number="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age)) <span class="op">+</span></a>
<a class="sourceLine" id="cb275-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> age))</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="09_tests_categorical_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Now we are ready for some modelling!</p>
<p>##Basic: One explanatory variable (predictor)</p>
<p>Lets find out what the influence of each predictor/confounding variable is on mortality from melanoma, which may help inform a more complicated regression, with multiple predictors/confounders.</p>
<p>We’ll start with whether the patient was male or female</p>
<p>###Worked example</p>
<p>First we need to create a regression model, using <code>glm()</code>, we will then summarise it using <code>summary()</code></p>
<p>Note, we need to use the <code>family</code> option. Specifying <code>'binomial'</code> in <code>family</code> tells <code>glm</code> to switch to logistic regression.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb277-1" data-line-number="1"><span class="co">#Create a model</span></a>
<a class="sourceLine" id="cb277-2" data-line-number="2"></a>
<a class="sourceLine" id="cb277-3" data-line-number="3"><span class="kw">glm</span>(died_melanoma.factor <span class="op">~</span><span class="st"> </span>sex.factor, <span class="dt">data =</span> mydata, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</a></code></pre></div>
<pre><code>## 
## Call:  glm(formula = died_melanoma.factor ~ sex.factor, family = &quot;binomial&quot;, 
##     data = mydata)
## 
## Coefficients:
##    (Intercept)  sex.factorMale  
##         -1.253           0.708  
## 
## Degrees of Freedom: 204 Total (i.e. Null);  203 Residual
## Null Deviance:       242.4 
## Residual Deviance: 237.4     AIC: 241.4</code></pre>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" data-line-number="1">model1 =<span class="st"> </span><span class="kw">glm</span>(died_melanoma.factor <span class="op">~</span><span class="st"> </span>sex.factor, <span class="dt">data =</span> mydata, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</a>
<a class="sourceLine" id="cb279-2" data-line-number="2"></a>
<a class="sourceLine" id="cb279-3" data-line-number="3"><span class="kw">summary</span>(model1)</a></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = died_melanoma.factor ~ sex.factor, family = &quot;binomial&quot;, 
##     data = mydata)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.9565  -0.7090  -0.7090   1.4157   1.7344  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -1.2528     0.2143  -5.846 5.03e-09 ***
## sex.factorMale   0.7080     0.3169   2.235   0.0254 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 242.35  on 204  degrees of freedom
## Residual deviance: 237.35  on 203  degrees of freedom
## AIC: 241.35
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Now we have created the model- fantastic!</p>
<p>But this doesn’t mean a lot to humans reading a paper- or us in fact.</p>
<p>The estimate output of <code>summary(model_1)</code> represents the logarithm of the odds ratio. The odds ratio would be a lot easier to understand.</p>
<p>Therefore, to sort that out we should exponentiate the output of the model! The <code>exp()</code> function will do this.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" data-line-number="1"><span class="kw">exp</span>(model1<span class="op">$</span>coefficients)</a></code></pre></div>
<pre><code>##    (Intercept) sex.factorMale 
##      0.2857143      2.0300000</code></pre>
<p>This gives us an odds ratio of 2.03 for males. That is to say, males are twice as likely to die from melanoma than females.</p>
<p>Now a confidence interval might be handy. As this will be the logarithm of the confidence interval, we should exponentiate it to make it understandable.</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb283-1" data-line-number="1"><span class="kw">exp</span>(<span class="kw">confint</span>(model1))</a></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                    2.5 %    97.5 %
## (Intercept)    0.1843592 0.4284939
## sex.factorMale 1.0914854 3.7938450</code></pre>
<p>The 2.5% is the lower bound and the 97.5% is the upper bound of the 95% confidence interval.</p>
<p>So we can therefore say that being male doubles your chances of dying from melanoma with an Odds Ratio of 2.03 (95% confidence interval of 1.09 to 3.79)</p>
<p>###Exercise</p>
<p>Repeat this for all the variables contained within the data, particulary:</p>
<p><code>stage.factor</code>, <code>age</code>, <code>ulcer.factor</code>, <code>thickness</code> and <code>age.factor</code>.</p>
<p>Write their odds ratios and 95% confidence intervals down for the next section!</p>
<p>Congratulations on building your first regression model in R!</p>
<p>##Summarizer package</p>
<p>We have developed our <code>summarizer</code> package to help with advanced regression modelling. We will introduce it here, but not go into detail.</p>
<p>Most packages can be installed with just <code>install.packages(&quot;package-name&quot;)</code>, e.g. <code>install.packages(&quot;survival&quot;)</code>.</p>
<p>Summarizer is still in development and can be installed with <code>install.packages(&quot;devtools&quot;)</code> followed by <code>devtools::install_github(&quot;ewenharrison/summarizer&quot;)</code>. See <a href="https://github.com/ewenharrison/summarizer" class="uri">https://github.com/ewenharrison/summarizer</a> for more information and updates.</p>
<p>##Summarise a list of variables by another variable</p>
<p>We can use the summarizer package to summarise a list of variables by another variable. This is very useful for “Table 1” in many studies.</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" data-line-number="1"><span class="kw">library</span>(summarizer)</a></code></pre></div>
<pre><code>## Loading required package: Hmisc</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<pre><code>## Loading required package: Formula</code></pre>
<pre><code>## 
## Attaching package: &#39;Hmisc&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     src, summarize</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     format.pval, units</code></pre>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb294-1" data-line-number="1">dependent=<span class="st">&quot;died_melanoma.factor&quot;</span></a>
<a class="sourceLine" id="cb294-2" data-line-number="2">explanatory =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;sex.factor&quot;</span>)</a>
<a class="sourceLine" id="cb294-3" data-line-number="3"></a>
<a class="sourceLine" id="cb294-4" data-line-number="4">mydata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb294-5" data-line-number="5"><span class="st">  </span><span class="kw">summary.factorlist</span>(dependent, explanatory, <span class="dt">p =</span> <span class="ot">TRUE</span>) -&gt;<span class="st"> </span>table_result</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">label</th>
<th align="left">levels</th>
<th align="right">No</th>
<th align="right">Yes</th>
<th align="right">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="left">Mean (SD)</td>
<td align="right">51.5 (16.1)</td>
<td align="right">55.1 (17.9)</td>
<td align="right">0.189</td>
</tr>
<tr class="even">
<td align="left">sex.factor</td>
<td align="left">Female</td>
<td align="right">98 (77.8)</td>
<td align="right">28 (22.2)</td>
<td align="right">0.024</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Male</td>
<td align="right">50 (63.3)</td>
<td align="right">29 (36.7)</td>
<td align="right"></td>
</tr>
</tbody>
</table>
<p>##<code>summarizer</code> function for logistic regression</p>
<p>We can then use the <code>summarizer</code> function to run a logistic regression analysis with similar syntax.</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb295-1" data-line-number="1">dependent=<span class="st">&quot;died_melanoma.factor&quot;</span></a>
<a class="sourceLine" id="cb295-2" data-line-number="2">explanatory =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;sex.factor&quot;</span>)</a>
<a class="sourceLine" id="cb295-3" data-line-number="3"></a>
<a class="sourceLine" id="cb295-4" data-line-number="4">mydata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb295-5" data-line-number="5"><span class="st">  </span><span class="kw">summarizer</span>(dependent, explanatory) -&gt;<span class="st"> </span>model2</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">label</th>
<th align="left">levels</th>
<th align="right">No</th>
<th align="right">Yes</th>
<th align="right">OR (univariable)</th>
<th align="right">OR (multivariable)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sex.factor</td>
<td align="left">Female</td>
<td align="right">98 (66.2)</td>
<td align="right">28 (49.1)</td>
<td align="right">-</td>
<td align="right">-</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Male</td>
<td align="right">50 (33.8)</td>
<td align="right">29 (50.9)</td>
<td align="right">2.03 (1.09-3.79, p=0.025)</td>
<td align="right">2.03 (1.09-3.79, p=0.025)</td>
</tr>
</tbody>
</table>

<p>##Adjusting for multiple variables in R</p>
<p>Your first models only included one variable. It’s time to scale them up.</p>
<p>Multivariable models take multiple variables and estimates how each variable predicts an event. It adjusts for the effects of each one, so you end up with a model that calculates the adjusted effect estimate (i.e. the odds ratio), upon an outcome.</p>
<p>When you see the term ‘adjusted’ in scientific papers, this is what it means.</p>
<p>###Worked Example</p>
<p>Lets adjust for <code>age</code> (as a continuous variable), <code>sex.factor</code> and <code>stage.factor</code>. Then output them as odds ratios.</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb296-1" data-line-number="1">dependent=<span class="st">&quot;died_melanoma.factor&quot;</span></a>
<a class="sourceLine" id="cb296-2" data-line-number="2">explanatory =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;sex.factor&quot;</span>, <span class="st">&quot;stage.factor&quot;</span>)</a>
<a class="sourceLine" id="cb296-3" data-line-number="3"></a>
<a class="sourceLine" id="cb296-4" data-line-number="4">mydata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb296-5" data-line-number="5"><span class="st">  </span><span class="kw">summarizer</span>(dependent, explanatory) -&gt;<span class="st"> </span>model3</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">label</th>
<th align="left">levels</th>
<th align="right">No</th>
<th align="right">Yes</th>
<th align="right">OR (univariable)</th>
<th align="right">OR (multivariable)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="left">Mean (SD)</td>
<td align="right">51.5 (16.1)</td>
<td align="right">55.1 (17.9)</td>
<td align="right">1.01 (0.99-1.03, p=0.163)</td>
<td align="right">1.01 (0.99-1.03, p=0.534)</td>
</tr>
<tr class="even">
<td align="left">sex.factor</td>
<td align="left">Female</td>
<td align="right">98 (66.2)</td>
<td align="right">28 (49.1)</td>
<td align="right">-</td>
<td align="right">-</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Male</td>
<td align="right">50 (33.8)</td>
<td align="right">29 (50.9)</td>
<td align="right">2.03 (1.09-3.79, p=0.025)</td>
<td align="right">1.62 (0.81-3.21, p=0.167)</td>
</tr>
<tr class="even">
<td align="left">stage.factor</td>
<td align="left">Stage I</td>
<td align="right">18 (12.2)</td>
<td align="right">1 (1.8)</td>
<td align="right">-</td>
<td align="right">-</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Stage II</td>
<td align="right">32 (21.6)</td>
<td align="right">5 (8.8)</td>
<td align="right">2.81 (0.41-56.12, p=0.362)</td>
<td align="right">2.83 (0.40-56.96, p=0.363)</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Stage III</td>
<td align="right">75 (50.7)</td>
<td align="right">29 (50.9)</td>
<td align="right">6.96 (1.34-128.04, p=0.065)</td>
<td align="right">7.17 (1.37-132.38, p=0.061)</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">Stage IV</td>
<td align="right">23 (15.5)</td>
<td align="right">22 (38.6)</td>
<td align="right">17.22 (3.13-322.85, p=0.008)</td>
<td align="right">14.30 (2.54-270.31, p=0.014)</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb297-1" data-line-number="1"><span class="kw">or.plot</span>(mydata, dependent, explanatory)</a></code></pre></div>
<pre><code>## Loading required package: scales</code></pre>
<pre><code>## 
## Attaching package: &#39;scales&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     discard</code></pre>
<pre><code>## The following object is masked from &#39;package:readr&#39;:
## 
##     col_factor</code></pre>
<pre><code>## Waiting for profiling to be done...
## Waiting for profiling to be done...</code></pre>
<pre><code>## Warning: Removed 2 rows containing missing values (geom_errorbarh).</code></pre>
<p><img src="09_tests_categorical_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Note- when we enter age into regression models, the effect estimate is provided in terms of per unit increase. So in this case it’s expressed in terms of an odds ratio per year increase (i.e. for every year in age gained odds of death increases by 1.02).</p>
<p>###Exercise</p>
<p>Now you try making a regression that includes <code>ulcer.factor</code>.</p>

<p>##Advanced: Fitting the best model</p>
<p>Now we have our preliminary model. We could leave it there.</p>
<p>However, when you publish research, you are often asked to supply a measure of how well the model fitted the data.</p>
<p>There are different approaches to model fitting. Come to our course HealthyR-Advanced: Practical Logistic Regression. At this we describe use of the Akaike Information Criterion (AIC) and the C-statistic.</p>
<p>The C-statistic describes discrimination and anything over 0.60 is considered good. The closer to 1.00 the C-statistic is, the better the fit.</p>
<p>The AIC measure model fit with lower values indicating better fit.</p>
<p>These metrics are available here:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb304-1" data-line-number="1">mydata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb304-2" data-line-number="2"><span class="st">  </span><span class="kw">summarizer</span>(dependent, explanatory, <span class="dt">metrics=</span><span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## Waiting for profiling to be done...
## Waiting for profiling to be done...
## Waiting for profiling to be done...
## Waiting for profiling to be done...</code></pre>
<pre><code>## [[1]]
##          label    levels          No         Yes
## 1          age Mean (SD) 51.5 (16.1) 55.1 (17.9)
## 2   sex.factor    Female   98 (66.2)   28 (49.1)
## 3                   Male   50 (33.8)   29 (50.9)
## 4 stage.factor   Stage I   18 (12.2)     1 (1.8)
## 5               Stage II   32 (21.6)     5 (8.8)
## 6              Stage III   75 (50.7)   29 (50.9)
## 7               Stage IV   23 (15.5)   22 (38.6)
##               OR (univariable)           OR (multivariable)
## 1    1.01 (0.99-1.03, p=0.163)    1.01 (0.99-1.03, p=0.534)
## 2                            -                            -
## 3    2.03 (1.09-3.79, p=0.025)    1.62 (0.81-3.21, p=0.167)
## 4                            -                            -
## 5   2.81 (0.41-56.12, p=0.362)   2.83 (0.40-56.96, p=0.363)
## 6  6.96 (1.34-128.04, p=0.065)  7.17 (1.37-132.38, p=0.061)
## 7 17.22 (3.13-322.85, p=0.008) 14.30 (2.54-270.31, p=0.014)
## 
## [[2]]
## [1] &quot;Number in dataframe = 205, Number in model = 205, Missing = 0, AIC = 232.3, C-statistic = 0.708&quot;</code></pre>
<p>###Extra material: Diagnostics plots</p>
<p>While outwith the objectives of this course, diagnostic plots for <code>glm</code> models can be produced by:</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb307-1" data-line-number="1"><span class="kw">plot</span>(model1)</a></code></pre></div>
<p><img src="09_tests_categorical_files/figure-html/unnamed-chunk-19-1.png" width="288" /><img src="09_tests_categorical_files/figure-html/unnamed-chunk-19-2.png" width="288" /><img src="09_tests_categorical_files/figure-html/unnamed-chunk-19-3.png" width="288" /><img src="09_tests_categorical_files/figure-html/unnamed-chunk-19-4.png" width="288" /></p>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="definitions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="time-to-event-data-survival.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/SurgicalInformatics/healthyr_book/edit/master/09_tests_categorical.Rmd",
"text": "Edit"
},
"download": ["healthyr-book.pdf", "healthyr-book.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
